spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organizer
    username: org_user
    password: '{cipher}AQCUor76idQruJD+Gdg5+juUJXi5pauF/oonnvFWs5PmEO4MpD+yt2WibfCfSilFVRWbpqHTJb9UdVSdOioX/Skbwm1hFXc5UThJYQAr4tfkE9nJzQ8hx/yS1DrcQbeyBMsgw2JKI7N6U6yV32zWV52MSLemFbHB1oLMirF5SLna1riWpfk+pSePpPG8pq0seFLY3L5gHO9IYHzcFNYl757bFVhnCNH/e3VtFDugAzEsIcGa04q9OdWFRHA/ChaXRJSZdKVSn2ttmQh81zkeroyov9e3KcVdABRaoREr8O//Xla3jXywMqiav94CwTNrp+1XslWs+vRB+zCssIVjzLeQZK6p3Ze7ZWMSHs0Kyop+CUevsB/TaqL3LEsI+tnkRDI='
    driverClassName: com.mysql.jdbc.Driver
