spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organizer
    username: org_user
    password: '{cipher}AQADpxViq0JPuO9sCWklR4eXuEexzZ5be4DL5L4igR3oLPwaKEsiHdYb+hkiMAK3me5vQruI3cYaQmKKKBexG4tVDVtDBmzlK9jrn9YXZSdUjnsBvUH80+9ihXwh6anR7q1BgmtTPdWGYic0wfcTuj+CGCOiJUAbLAa4MuXbGKxWN1yVJ/ydiNu7R9FPaIUFwevmCaeAVtzeBL/Yy7QIYxVhiEtapTmQCZf8pOUKIqCNACe8hR24cVKhZq6cUZGwoLMDjb8uxVVCJ4vlq2lw1WuxzOQXrcG2IHi3rkhdGp0ky03nfT5KTPxpW6b5F1SG/XGCNEIGyYCEGAe7uew4Z7V3Q3bSqVkUO0t9NmMx1YKOtWvvQKjh771wSZiq+qWvIug='
    driverClassName: com.mysql.jdbc.Driver
